import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./providers";
import { ApolloWrapper } from "./lib/appolo-client";
import { SessionProvider } from "./lib/session-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          <ApolloWrapper>
            <Providers>{children}</Providers>
          </ApolloWrapper>
        </body>
      </html>
    </SessionProvider>
  );
}
